"""Added updated_at in privacy_request table

Revision ID: 7d9ef9eb0795
Revises: 48a0dd6b4650
Create Date: 2026-05-17 20:56:59.586534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9ef9eb0795'
down_revision: Union[str, Sequence[str], None] = '48a0dd6b4650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privacy_requests', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privacy_requests', 'updated_at')
    # ### end Alembic commands ###
